commands:
  #Hora
  -commmand:
    input:  que horas são?
    entity: time
    action: getTime
  -commmand:
    input: Me diga horas.
    entity: time
    action: getTime
  -commmand:
    input: que horas são?
    entity: time
    action: getTime
  -commmand:
    input: hora.
    entity: time
    action: getTime
  -commmand:
    input: ora.
    entity: time
    action: getTime
  -commmand:
    input: qual o horario?
    entity: time
    action: getTime
  #Data
  -commmand:
    input: Qual é a data de hoje?
    entity: time
    action: getDate
  -commmand:
    input: Data de hoje?
    entity: time
    action: getDate
  -commmand:
    input: Data certa.
    entity: time
    action: getDate
  # Tempo
  -commmand:
    input: Previsão do tempo
    entity: weather
    action: getweather
  -commmand:
    input: como está o tempo hoje?
    entity: weather
    action: getweather
  #open
  -commmand:
    input: Abrir google
    entity: open
    action:
  -commmand:
    input: Abra youtube
    entity: open
    action: